### PR TITLE
Adopt a uniform toString() format 220

### LINKED ISSUE #220: Adopt a uniform toString() format
We currently have all kinds of `toString()` string representations in our code base. Making them uniform will help us easily identify object string representations and their containing data in places like logs, JUnit test failure messages etc.

Note, however, that some user-facing messages depend on the `toString()` representations. These should be migrated to use formatting methods that are specialized for user-facing messages instead.

Maybe use Guava's [`MoreObjects.toStringHelper()`](https://github.com/google/guava/wiki/CommonObjectUtilitiesExplained#tostring)

### PR DESCRIPTION
**Pull request by nsaiisasidhar**
Fixes #220 

Please let me know whether it looks good and if more changes has to be made.

### CODE REVIEW

**Comment by damithc** [comment]
@nsaiisasidhar please fix CI failures.

**Comment by MightyCupcakes** [comment]
Should this PR standardise all toString() methods in the codebase?

Perhaps this daunting task can be split into smaller PRs?

**Comment by damithc** [comment]
@nsaiisasidhar I think it's best if you complete a `d.FirstTimer` issue first. I'm putting this PR on hold until then.

**Comment by damithc** [comment]
Closing due to inactivity. @nsaiisasidhar Please reopen when ready to resume.

**Pull request closed without merging**
