### PR TITLE
Checkstyle: require default branch in switch statements #319

### PR DESCRIPTION
**Pull request by eugenepeh**
Addition to #319

### CODE REVIEW

**Comment by eugenepeh** [comment]
comment header for module is not included due to self explanatory.

**Comment by CanIHasReview** [comment]
# v1

@eugenepeh submitted v1 for review.

* [v1 1/1] [Checkstyle: add MissingSwitchDefault rule](https://github.com/se-edu/addressbook-level4/pull/378/commits/5a19166ef69a0f96532dc8d2c2eefa97cd173d50)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/aa9b3b392f5264260d60403c0c9715171692b1d4...5a19166ef69a0f96532dc8d2c2eefa97cd173d50))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/378/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v2

@eugenepeh submitted v2 for review.

* [v2 1/1] [Checkstyle: add MissingSwitchDefault rule](https://github.com/se-edu/addressbook-level4/pull/378/commits/9c9b735605b368612876ce1cbb51cb11ad1718d0)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/aa9b3b392f5264260d60403c0c9715171692b1d4...9c9b735605b368612876ce1cbb51cb11ad1718d0)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/86eac7c8f06cc808a57fd2d653cb268769f9ed02~1...86eac7c8f06cc808a57fd2d653cb268769f9ed02))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/378/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@eugenepeh submitted v3 for review.

* [v3 1/1] [Checkstyle: add MissingSwitchDefault rule](https://github.com/se-edu/addressbook-level4/pull/378/commits/4ca54ce13a165f3f335141162f60217afe6ae050)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/6951a73c502185c54370c16fde85605743899d55...4ca54ce13a165f3f335141162f60217afe6ae050)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/a9f59d82fd35e3ba6edfa83f542c230cd6dfbe9f~1...a9f59d82fd35e3ba6edfa83f542c230cd6dfbe9f))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/378/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Pull request merged**
