### PR TITLE
Load UserGuide in the help window. #11

### LINKED ISSUE #11: Load UserGuide in the help window.
Currently outdated. Things like hotkey to resize application should be removed.

### PR DESCRIPTION
**Pull request by lejolly**
Fixes #11

### CODE REVIEW

**Comment by damithc** [comment]
I meant load it directly from GitHub, like we load Google search pages.

**Comment by lejolly** [comment]
do i remove the existing html file?

**Comment by lejolly** [comment]
additionally, do i just link to the level 3 `UserGuide.md`? or do i copy everything over from level 3?

**Comment by damithc** [comment]
Level 4 user guide is awaiting merge #68

**Comment by lejolly** [comment]
ok, i'll wait for the merge to happen first then.

**Comment by damithc** [comment]
Yes, can remove the html file. We'll switch back to a local html version in a future version.

**Comment by damithc** [comment]
User guide merged. Can go ahead.

**Comment by lejolly** [comment]
ok done.

**Comment by damithc** [comment]
@lejolly can you update the `UserGuide.md`? `view` -> `select`

**Comment by lejolly** [comment]
ok, should i remove the `Changing the save location` section?

**Comment by damithc** [comment]
I thought we support that feature (level 3 did). But if we don't have it, can remove.

**Comment by lejolly** [comment]
ok done.

**Pull request merged**
