### PR TITLE
Allow running tests through Gradle on JDK 10

### LINKED ISSUE #884: Cannot run tests through gradle on JDK 10
Hi there,

I have setup the project in the steps laid out in the setup section of the documentation but I get errors when trying to run the tests through gradle with the `gradlew clean allTests` or `gradlew clean headless allTests` commands.

I can run the app and the tests (all passing) just fine through IntelliJ.

I am on Windows 10, Using Java JDK 10.0.1 and the most recent version of IntelliJ.

Here is the log file.
[log.txt](https://github.com/se-edu/addressbook-level4/files/1966123/log.txt)

I have done a bit of searching on the internet but can't seem to find anything helpful.

Any help would be greatly appreciated :)

### LINKED ISSUE #886: Upgrade gradle to latest version
Following the Java 10 release, Gradle 4.7 is the first, and the latest version, that supports this update.

Let's update gradle wrapper to use the latest version.

### PR DESCRIPTION
**Pull request by pyokagan**
Fixes #884 
Fixes #886 

```
Upgrade our Gradle version to 4.8.1 so as to allow JDK 10 installations
to run our tests successfully.

Due to a JavaFX bug, JDK 10 on Windows will fail to run tests in
headless mode. Update our documentation and build.gradle script to warn
devs against using JDK 10 on Windows, and recommend that they use JDK 9
instead.
```

### CODE REVIEW

**Comment by yamgent** [comment]
Running `allTests` seems OK now, however, running `allTests` with `headless` still causes an error:

```
PS C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\addressbook-level4> ./gradlew headless allTests

> Task :headless
Setting headless mode properties.

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testfx.toolkit.impl.ApplicationLauncherImpl (file:/C:/Users/Tan%20Wang%20Leng/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-core/4.0.12-alpha/55d68835a7f5c0f3b5630a2a542e0880f2548e7f/testfx-core-4.0.12-alpha.jar) to field com.sun.glass.ui.PlatformFactory.instance
WARNING: Please consider reporting this to the maintainers of org.testfx.toolkit.impl.ApplicationLauncherImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8eb034e80, pid=108, tid=13276
#
# JRE version: Java(TM) SE Runtime Environment (10.0.1+10) (build 10.0.1+10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (10.0.1+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [javafx_font.dll+0x4e80]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\addressbook-level4\hs_err_pid108.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:2178'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:134)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:115)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
        at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:473)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:272)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:260)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:254)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:132)
        ... 7 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 10' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the user guide at https://docs.gradle.org/4.6/userguide/java_plugin.html#sec:test_execution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
9 actionable tasks: 2 executed, 7 up-to-date
```

**Comment by pyokagan** [comment]
@yamgent 
> Running allTests seems OK now, however, running allTests with headless still causes an error. Reproducible on your side?

Nope (on Linux), otherwise I'd have known beforehand since I tested with `gradlew headless allTest` myself :S

> ```
> # C  [javafx_font.dll+0x4e80]
> ```

This suggests that this is a separate JavaFX-related problem.

**Comment by yamgent** [comment]
> This suggests that this is a separate JavaFX-related problem.

OK. Someone else with Windows will probably have to check whether they are getting the same issue then (to exclude the possibility that I screwed up the Java installation or something).

**Comment by pyokagan** [comment]
@yamgent @yamidark Any idea why this might be happening?

**Comment by eugenepeh** [comment]
Looks like a similar issue to this https://stackoverflow.com/questions/41065861/gradle-messageioexception-could-not-write-message-endofstream-to-127-0-0-1?rq=1

**Comment by yamgent** [comment]
@pyokagan The maintainer of TestFX ran into a similar issue: https://github.com/javafxports/openjdk-jfx/issues/66

According to [this comment](https://github.com/javafxports/openjdk-jfx/issues/66#issuecomment-384267992), it seems to be a bug on JavaFX end. Apparently they forgot to call some initialisation methods when using Windows' DirectWrite library (the GUI renderer used by JavaFX on Windows):

> We roughly know what the problem is: Some initialization that is done by either the D3D pipeline or Glass (either is sufficient) is needed to allow the DirectWrite calls used by the native font code to work.

The [current appveyor build](https://ci.appveyor.com/project/damithc/addressbook-level4/build/1.0.3891) shows traces of the error. Our previous PRs did not have appveyor failing, so  migrating to JaCoCo 0.8.1 is partially responsible for the error.

But if it is a JavaFX problem, I don't think we can do much about it, unless we can find some temporary workarounds.

I guess that's the risk we take by upgrading to new technologies too soon, since their stability cannot be taken for granted. :P.

**Comment by pyokagan** [comment]
@yamgent 
> The maintainer of TestFX ran into a similar issue: javafxports/openjdk-jfx#66 According to this comment, it seems to be a bug on JavaFX end.

Oh, I see. Nice find :+1: 

> The current appveyor build shows traces of the error.

If you meant:

```
WARNING: Illegal reflective access by org.testfx.toolkit.impl.ApplicationLauncherImpl (file:/C:/Users/appveyor/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-core/4.0.12-alpha/55d68835a7f5c0f3b5630a2a542e0880f2548e7f/testfx-core-4.0.12-alpha.jar) to field com.sun.glass.ui.PlatformFactory.instance
WARNING: Please consider reporting this to the maintainers of org.testfx.toolkit.impl.ApplicationLauncherImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

That's because of https://github.com/TestFX/TestFX/issues/553

> Our previous PRs did not have appveyor failing, so migrating to JaCoCo 0.8.1 is partially responsible for the error.

That's because of #881  If @damithc restarts the build enough times, it should pass. Unfortunately it's quite hard to ensure PRs pass AppVeyor because if it stalls, I'll need to wait 1 hour for it to time out.

**Comment by pyokagan** [comment]
I'll update the developer guide to *strongly recommend* Windows users to use JDK 9.

**Comment by eugenepeh** [comment]
https://docs.gradle.org/current/release-notes.html 

Btw... it seems that the wrapper is still using 4.6. Would upgrading to 4.7 helps?

**Comment by eugenepeh** [comment]
```
https://docs.gradle.org/current/release-notes.html

Btw... it seems that the wrapper is still using 4.6. Would upgrading to 4.7 helps?
```

nvm tried it on my machine... doesn't work

**Comment by pyokagan** [comment]
@yamgent 
> I think this will be asked a lot by students, so we may need to jot this down somewhere.

Yeah, someone else will need to do this. I'm just volunteering in my free time now.

**Comment by pyokagan** [comment]
build.gradle: need to change all references of gradle 4.6 to `4.8.1`

**Pull request merged**
