### PR TITLE
UrlUtil is unused #308

### LINKED ISSUE #308: UrlUtil is unused
[`UrlUtil`](https://github.com/se-edu/addressbook-level4/blob/d741336a16662b675c117ed2aa3ade11a934f24c/src/main/java/seedu/address/commons/util/UrlUtil.java) is unused and should be removed.

### PR DESCRIPTION
**Pull request by ylhlh**
Fixes #308 
Ready for review

### CODE REVIEW

**Comment by eugenepeh** [comment]
Hi @ylhlh, 

don't forget to use CanIHasReview when you're ready
Checkout 
https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md
if you have not use it before

**Comment by CanIHasReview** [comment]
# v1

@ylhlh submitted v1 for review.

* [v1 1/3] [Remove UrlUtilTest ](https://github.com/se-edu/addressbook-level4/pull/325/commits/47083f930f72e4c5a67e762268306afc27f28336)
* [v1 2/3] [Remove UrlUtil ](https://github.com/se-edu/addressbook-level4/pull/325/commits/0f82161ece25760309cbb5a2124803c96f0160c2)
* [v1 3/3] [Remove UrlUtilTest as unit test example ](https://github.com/se-edu/addressbook-level4/pull/325/commits/4184a8ea33bf71de8991177c702835ae6395ae89)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...4184a8ea33bf71de8991177c702835ae6395ae89))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/325/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by MightyCupcakes** [comment]
Your changes can probably be made in one commit. In my opinion, removing unit tests and the unit under test itself should be done in one atomic operation.

**Comment by CanIHasReview** [comment]
# v2

@ylhlh submitted v2 for review.

* [v2 1/1] [Remove UrlUtil\, UrlUtilTest ](https://github.com/se-edu/addressbook-level4/pull/325/commits/228d822be96a5cb862b9ac27163b0e68a39d0e06)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...228d822be96a5cb862b9ac27163b0e68a39d0e06)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/66a09b8d94eaac3ace75cec2fb7734a8bbc32b5c~1...66a09b8d94eaac3ace75cec2fb7734a8bbc32b5c))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/325/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@ylhlh submitted v3 for review.

* [v3 1/1] [Remove unused UrlUtil and UrlUtilTest classes ](https://github.com/se-edu/addressbook-level4/pull/325/commits/735955543f86a6e8372116e465d913312099b4fc)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/65fdb4818f191c27f46846588172f644483718af...735955543f86a6e8372116e465d913312099b4fc)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/b9c5f4fad2cfb2a7774e643205da91aed2a79300~1...b9c5f4fad2cfb2a7774e643205da91aed2a79300))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/325/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
Thanks for the contribution @ylhlh

**Pull request merged**
