### PR TITLE
Remove unused code in TestUtil #222

### LINKED ISSUE #222: Remove unused code in TestUtil
There are lots of unused methods in [`TestUtil`](https://github.com/se-edu/addressbook-level4/blob/311ab3c0ccd4d6e49d81234e6d8fe42646e3c834/src/test/java/seedu/address/testutil/TestUtil.java).

Remove them.

### PR DESCRIPTION
**Pull request by MightyCupcakes**
Closes #222 

Removed the following unused methods:

* TestUtil#main()
* TestUtil#isHeadlessEnvironment()
* TestUtil#captureScreenShot()
* TestUtil#descOnFail()
* TestUtil#setFinalStatic()
* TestUtil#initRuntime()
* TestUtil#tearDownRuntime()
* TestUtil#getPrivateMethod()
* TestUtil#renameFile()
* TestUtil#getSceneMidPoint()
* TestUtil#getScenePos()
* TestUtil#getSceneMaxX()
* TestUtil#getSceneMaxY()
* TestUtil#getLastElement()
* TestUtil#replacePersonFromList()

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@MightyCupcakes submitted v1 for review.

* [v1 1/1] [TestUtil: Remove unused public methods](https://github.com/se-edu/addressbook-level4/pull/290/commits/e1629664f1cb05e294b478151e0cc293c4530732)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/aaff772f1989c11e294c264246da16453876bad1...e1629664f1cb05e294b478151e0cc293c4530732))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/290/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v2

@MightyCupcakes submitted v2 for review.

* [v2 1/1] [TestUtil: Remove unused public methods](https://github.com/se-edu/addressbook-level4/pull/290/commits/5bf5bd6a9a8cbdfb275c016cf302b808eed06a2b)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/f40ee42cb2e29a99c9c6b8757b64b0b0f4284d67...5bf5bd6a9a8cbdfb275c016cf302b808eed06a2b)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/1e5b2ba7535365e97c0f35e8c73a551e581132c5~1...1e5b2ba7535365e97c0f35e8c73a551e581132c5))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/290/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@MightyCupcakes submitted v3 for review.

* [v3 1/1] [TestUtil: Remove unused methods ](https://github.com/se-edu/addressbook-level4/pull/290/commits/f8824a3658fb8224a028bb79dfea1ac3ca52a4c8)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/1eeb6fb0a75d11d317390588f6799edb52f33047...f8824a3658fb8224a028bb79dfea1ac3ca52a4c8)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/ff83a0804353a40d76939758cb63b514482042bb~1...ff83a0804353a40d76939758cb63b514482042bb))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/290/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
> In general you may wish to explore a more thorough cleanup of TestUtil.

@MightyCupcakes create another issue for this?

**Comment by MightyCupcakes** [comment]
`GuiRobot#push()` is called here [MainMenuHandle.java](https://github.com/se-edu/addressbook-level4/blob/941d0afebe52dc6bd86b60bd4a11861f48273900/src/test/java/guitests/guihandles/MainMenuHandle.java#L34) which is used by `HelpWindowTest` to test the F1 key functionality. 

`TestUtil#asList()` is used in `TestUtil#addPersonsToList()` but that can probably be refactored.

**Comment by pyokagan** [comment]
@MightyCupcakes 
> GuiRobot#push() is called here MainMenuHandle.java which is used by HelpWindowTest to test the F1 key functionality.

That calls `org.testfx.api.FxRobot#push(KeyCode...)`, not `guitests.GuiRobot#push(KeyCodeCombination)`

**Pull request merged**
