### PR TITLE
Travis CI: cache dependencies #342

### LINKED ISSUE #342: Travis CI: cache dependencies
We don't seem to be caching dependencies in our Travis builds. It would probably help shorten build time if we could cache them and avoid having to download them every build.

### PR DESCRIPTION
**Pull request by chao1995**
Fixes #342 

Ready for review.

### CODE REVIEW

**Comment by chao1995** [comment]
In [travis page](https://travis-ci.org/se-edu/addressbook-level4/caches), we can see that it has cached ~139 MB of dependencies.

**Comment by CanIHasReview** [comment]
# v1

@chao1995 submitted v1 for review.

* [v1 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/4ac4789d1ffb96722199195963c2a39d69c838a7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...4ac4789d1ffb96722199195963c2a39d69c838a7))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
Also does this work for the current PR only atm?

**Comment by chao1995** [comment]
> Also does this work for the current PR only atm?

Haha. Good question. My guess is yes (coz travis should use the old .travis.yml to start the job for other PRs). But we'll know for sure when the next build from other PRs comes.

**Comment by yamgent** [comment]
I see. I tried it on my repo by checking out your branch, but it seems to make little difference to my build times when I added new commits to the branch (in fact, the commit that makes the caches ends up prolonging the build by 40 seconds instead :/):

travisbuild

**Comment by chao1995** [comment]
@yamgent 

So I just did a closer examination over the time spent at each part of the build process.

With cache, as in [this build](https://travis-ci.org/yamgent/addressbook-level4/builds/213260219), there is no time spent in installing the dependencies, so it took ~10 seconds.

screen shot 2017-03-21 at 1 40 44 pm

And in the end, there is some overhead to store the cache, which took ~ 2 seconds. so in total ~12 seconds.

screen shot 2017-03-21 at 1 43 25 pm


Without cache, as in [this build](https://travis-ci.org/yamgent/addressbook-level4/builds/212866323), the installation took ~26 seconds.

screen shot 2017-03-21 at 1 46 52 pm

So the speedup is about 10~15 seconds. (will update commit message about this)

Previously I look at the time by the total time. But there may be some difference in setting up, running tests. A better measure will be just looking at the part of installing dependencies.

**Comment by CanIHasReview** [comment]
# v2

@chao1995 submitted v2 for review.

* [v2 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/94780ceec8437a2d7fe5677a9f7d283bf00fae08)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...94780ceec8437a2d7fe5677a9f7d283bf00fae08)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/1e1e79d2d663cff04c3f7a311019156e817e54d5~1...1e1e79d2d663cff04c3f7a311019156e817e54d5))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@m133225 can have a look?

**Comment by chao1995** [comment]
> Can consider mentioning total build time, ten seconds out of how many?

But the total build time can vary quite a lot from 4 minutes 50 seconds to sometimes over 6 minutes.  It's rather hard to give an expected average as well. But the 10 seconds can be quite clearly identified from the time spent on travis installing stage.

**Comment by CanIHasReview** [comment]
# v3

@chao1995 submitted v3 for review.

* [v3 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/52f0b969524d60526caa57785c3890e499708c8a)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/4c4e1ed78fd8465512c5b434a3c592da52740717...52f0b969524d60526caa57785c3890e499708c8a)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/201b361d4bc5e55db715079381415e89231e5fdb~1...201b361d4bc5e55db715079381415e89231e5fdb))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by chao1995** [comment]
Proposed merge commit message

> Gradle dependencies are not cached in Travis builds.<br>
Consequently, every new build will re-download the dependencies, which
will increase the build time by roughly ten seconds.<br>
Let's teach Travis to cache Gradle dependencies using the recommended
configurations from Travis CI documentation [1].<br>
[1] https://docs.travis-ci.com/user/languages/java/#Caching

**Comment by damithc** [comment]
@m133225 reminder

**Comment by chao1995** [comment]
@m133225 Thank you so much for providing the insights on how travis cache works.

**Comment by CanIHasReview** [comment]
# v4

@chao1995 submitted v4 for review.

* [v4 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/8783248bcf3789218eff0f00b64b4de89be16c4d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...8783248bcf3789218eff0f00b64b4de89be16c4d)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/43c085be2f8cc31cdc2d3a3d1f4d2056c9c1c92e~1...43c085be2f8cc31cdc2d3a3d1f4d2056c9c1c92e))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by chao1995** [comment]
@m133225 Updated commit message.

**Comment by m133225** [comment]
Looks fine to be aside from a couple of nitpicks.
>Consequently, the dependencies are re-download in every build.

`re-downloaded`
>Reasons for the time-saving may be because now Travis downloads the dependencies from
S3 in bulk, instead of making multiple requests for each dependency.

`Reasons for the shorter build time now may be because...`

**Comment by CanIHasReview** [comment]
# v5

@chao1995 submitted v5 for review.

* [v5 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/9c04b879ce6dd56386612982ba2f3af3bd147db1)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...9c04b879ce6dd56386612982ba2f3af3bd147db1)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/93fc69d275dc3934a886a6647fd10e1f90702173~1...93fc69d275dc3934a886a6647fd10e1f90702173))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v6

@chao1995 submitted v6 for review.

* [v6 1/1] [Travis CI: cache Gradle dependencies](https://github.com/se-edu/addressbook-level4/pull/347/commits/3d27ae5a4599a2ddad6c6338dbf74845d1415ca1)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e1eafd1145cb5fdcc81bbacecf9e5145903b3fe2...3d27ae5a4599a2ddad6c6338dbf74845d1415ca1)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/78479db89cb2f5c9cbd9f939288e5ee2b924cd69~1...78479db89cb2f5c9cbd9f939288e5ee2b924cd69))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/347/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by chao1995** [comment]
V6: "in the end" to "at the end".

**Comment by chao1995** [comment]
@damithc Prof, is this PR going to be merged?

**Pull request merged**
