### PR TITLE
Bring logic tests from level 3 #39

### LINKED ISSUE #39: Bring over Logic from level 3
If possible, we should introduce a Logic (and LogicTest), similar to level-3.

### LINKED ISSUE #76: Remove private fields form contact details
And clean up all associated logic

### LINKED ISSUE #77: Parser should not instantiate the individual contact details of a person

### LINKED ISSUE #78: Bring over other Model features from level 3

### PR DESCRIPTION
**Pull request by YijinL**
Fixes #39, fixes #76, fixes #77, fixes #78.

Logic integration test is now `CommandBoxTest`. 
Does not explicitly test javafx ui components. 
Tests that events have been raised correctly if needed, but does not check the receiving components' response to the events.

### CODE REVIEW

**Comment by YijinL** [comment]
@damithc commands are now fully covered except GUI

**Comment by YijinL** [comment]
After merging, everyone has to delete their storage file. (storage schema changed)

The file provided in `data/` is already updated, so that one can be kept.

**Comment by damithc** [comment]
Go ahead and merge @YijinL

**Comment by damithc** [comment]
@YijinL test duration decreased about 30 seconds although we added new tests. :-p Any idea why?

**Comment by YijinL** [comment]
Decreased compared to when? I think it may be the addcommandtest, your gui test refactoring made it faster (less repititive cases)

**Pull request merged**
