### PR TITLE
Set Up AppVeyor CI #192

### PR DESCRIPTION
**Pull request by pyokagan**
AppVeyor[1] is a continuous integration service used to build and test
projects on a Windows VM. Adding AppVeyor support to this project will
allow us to easily ensure that our tests do not break on Windows.

Add an appveyor.yml file that will teach AppVeyor how to build this
project and run its tests.

Update our documentation to explain to developers how to set up AppVeyor
on their own repositories.

[1] https://www.appveyor.com/

Ready for review.

### CODE REVIEW

**Comment by damithc** [comment]
@pyokagan can go ahead and merge. @m133225 can give comments later (if any). After this is merged, I'll follow the instructions to set AV for this repo.

**Comment by pyokagan** [comment]
@damithc Okay I'll fix up a minor error I noticed in the images and then merge.

**Comment by pyokagan** [comment]
@damithc Okay I think this is ready. Will merge as requested.

**Comment by damithc** [comment]
I've set it up. But the badge code has my username in it :-p
[Build status](https://ci.appveyor.com/project/damithc/addressbook-level4)
`[Build status](https://ci.appveyor.com/project/damithc/addressbook-level4)`

**Comment by pyokagan** [comment]
@damithc Yeah, I think AppVeyor doesn't have the concept of Github organizations, since it works with other services as well.

**Pull request merged**
