### PR TITLE
Checkstyle: enforce one variable declaration per line #319

### PR DESCRIPTION
**Pull request by eugenepeh**
Addition to #319

### CODE REVIEW

**Comment by eugenepeh** [comment]
@pyokagan understood that they're 2 different thing but this rule triggers even if you do something like this
> int a; int b; 

even though this check is already covered by single statement per line.

**Comment by pyokagan** [comment]
@eugenepeh 

> understood that they're 2 different thing but this rule triggers an error even if you do something like this
> 
>     int a; int b;
> 
> even though this check is already covered by single statement per line.
> so it is actually covering by per line basis rather than just per statement.

Oh, so sorry. Yes, you're absolutely right, and I see that you have noted that correctly in the comment in `checkstyle.xml`.

Still, please modify the commit message to mention both `statement` and `line` please, thanks. :-)

**Comment by eugenepeh** [comment]
@pyokagan oops... I just tested and realize... 
> int a,
    b;

This works too. So I don't think I can mention statement 😝

**Comment by pyokagan** [comment]
@eugenepeh Update the commit message to include the examples of code that you provided above which pass or fail the check.

**Pull request merged**
