### PR TITLE
MainApp: Update version number #575

### LINKED ISSUE #575: Lower the version number
Shall we delete existing releases and do a new release under a lower version number. e.g. `v0.6`? That's because the next batch of students will take this version move towards v2.0; I want them to use v1.0, v1.1, .. v1.5 in their iterations.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #575

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
What shall we put for the `tag`, `release title` and `description`?

I suppose tag is `v0.6`.

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [MainApp: Update version number](https://github.com/se-edu/addressbook-level4/pull/622/commits/238b373ac891d529548200d9fcc11df4b81f9c3d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/ecdd485a6efa74886e540f7b6e6acdbee30e32a1...238b373ac891d529548200d9fcc11df4b81f9c3d))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/622/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by damithc** [comment]
Yes v0.6 is fine. Nothing special for other two items. Just mention it is an intermediate/pre-production release for internal use.

**Comment by Zhiyuan-Amos** [comment]
@yamgent I've made the release, for your approval so that I can merge this in.

**Pull request merged**
