### PR TITLE
checkstyle: fix module name error #276

### LINKED ISSUE #276: checkstyle : module naming error
Module names such as ConstantNameCheck is not recognised by checkstyle plugin.

### PR DESCRIPTION
**Pull request by eugenepeh**
Fixes #276 
Ready for review

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@eugenepeh submitted v1 for review.

* [v1 1/1] [checkstyle: fix module name error ](https://github.com/se-edu/addressbook-level4/pull/279/commits/1047dd02bfa2b72d9472d7b766d8e49e60e2df82)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/da4dc8e78218b35ccf991108acf1c56ca8492f57...1047dd02bfa2b72d9472d7b766d8e49e60e2df82))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@eugenepeh does this mean the affected rules are not applied in the current version?

**Comment by eugenepeh** [comment]
@damithc I believe so since that 5 rules did not show up in the eclipse plugin before the change.

**Comment by damithc** [comment]
> I believe so since that 5 rules did not show up in the eclipse plugin before the change.

Just for our knowledge, may be you can try to break those rules and see  if the violations are reported by checkstyle? Check both eclipse way and gradle way.

**Comment by eugenepeh** [comment]
@damithc understood, will try it out and report the result shortly.

**Comment by eugenepeh** [comment]
###  Updates on findings, 

- Surprisingly, Eclipse, Gradle and Codacy are still able detect the coding violation with/without fixing the module name.

Further study on checkstyle repository, https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageObjectFactory.java -> createModule(String name) function shows that it actually appends "Check" to module names if it does not exist. This may be due to Checkstyle Configuration generator in Eclipse does not append "Check" to module names and it is required to create an object instance as all module's full names contains "Check" at the back, according to fillShortToFullModuleNamesMap() function. 

### Summary
Advantages of removing "Check" from module names :
- Standardization along with other module names
- Allows Checkstyle Configuration detects existing modules in configuration file.

Disadvantages
- Currently None

Not Affected 
- Gradle build report
- Eclipse warning
- Codacy issues breakdown

**Comment by damithc** [comment]
@yamgent your thoughts on @eugenepeh's update above? I thought we are using the default config file given by checkstyle which should be standardized already?

**Comment by yamgent** [comment]
While it is hard to tell the origin of the file (only the original committer of the file will know this), I suspect that we are actually not using the default config file given by checkstyle. I took a look at their standard [checkstyle config file](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) for Google's Java style, and they have been using `TypeName` instead of `TypeNameCheck` all along.

Therefore, I think that it would be a good idea to remove the `Check` suffix for the affected modules, because even the standard config file given by checkstyle do not use the suffix.

**Comment by m133225** [comment]
The addition of `Check` was introduced in a very early [commit](https://github.com/HubTurbo/HubTurbo/commit/5f930692af7398ca935cb260827e2094077c3e96) in HubTurbo. After some searching, it seems to be similar to the config file taken from [a Google's sample application](https://github.com/google/google-api-java-client-samples/blob/master/checkstyle.xml), so there probably wasn't a specific reason for adding the `Check` to the module name.

**Comment by eugenepeh** [comment]
In additionally,
Codacy's checkstyle works only if the checkstyle.xml is placed in project root 
(tested and confirmed with codacy support staff) even if Code Pattern -> Rules Configuration is set to scan for configuration file.

**Comment by damithc** [comment]
> After some searching, it seems to be similar to the config file taken from [a Google's sample API usage](https://github.com/google/google-api-java-client-samples/blob/master/checkstyle.xml)<s>application</s>, so there probably wasn't a specific reason for adding the `Check` to the module names.

@eugenepeh perhaps you can investigate (in a separate issue) the differences between our config file and the default file (or other model files such as the one by Google) to see how we deviate?

**Comment by damithc** [comment]
> Codacy's checkstyle works only if the checkstyle.xml is placed in project root
> (tested and confirmed with codacy support staff) even if Code Pattern -> Rules Configuration is set to scan for configuration file.

@eugenepeh  thanks for checking that. Is that a bug they plan to fix?

**Comment by eugenepeh** [comment]
>@eugenepeh perhaps you can investigate (in a separate issue) the differences between our config file and >the default file (or other model files such as the one by Google) to see how we deviate?

@damithc understood, I'm on it. I have also posted the questions on both stackoverflow and on checkstyle feedback forum yesterday, here's the link to both
http://stackoverflow.com/questions/41931046/checkstyle-module-name-constantname-vs-constantnamecheck
https://groups.google.com/forum/?hl=en#!topic/checkstyle/oQYGd9AriHE

>@eugenepeh thanks for checking that. Is that a bug they plan to fix?

@damithc they don't seems plan to fix that anytime soon, they advise me to stick to placing the configuration file in project root

**Comment by damithc** [comment]
> @damithc they don't seems like planning to fix that anytime soon, they advise me to stick to placing the configuration file in project root

I see. May be we should take a look at SonarCube as an alternative to codacy ( #281 )

**Comment by eugenepeh** [comment]
@yamgent I have done the requested changes, sorry for late notification, please let me know if any other changes is required

**Comment by yamgent** [comment]
@eugenepeh ok, thanks for the notification. Can you submit a new @CanIHasReview iteration on this PR? This will inform reviewers in the future that you are ready for review. :)

**Comment by CanIHasReview** [comment]
# v2

@eugenepeh submitted v2 for review.

* [v2 1/1] [checkstyle: fix module name error](https://github.com/se-edu/addressbook-level4/pull/279/commits/757d026e7b15c52f2dcd4874a0c45babe0c4c1bc)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...757d026e7b15c52f2dcd4874a0c45babe0c4c1bc)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/commit/04cb9a55f42030efee1b823ebf371c9c18547a82))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@eugenepeh submitted v3 for review.

* [v3 1/1] [checkstyle: fix module name error](https://github.com/se-edu/addressbook-level4/pull/279/commits/55385be83d3a194d70a011b513acc33b30b075f0)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...55385be83d3a194d70a011b513acc33b30b075f0)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/03cbab56bcccd67ec428b2b08dbf5449f6ef2b8c~1...03cbab56bcccd67ec428b2b08dbf5449f6ef2b8c))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by eugenepeh** [comment]
Hi @pyokagan,

If you go to Eclipse > Project Properties > Checkstyle > Configure...,
you can see that under Naming Conventions, the 5 modules with "Check" in their name,
doesn't shows up in the list and was ignored silently.
It may be hard to tell that whether they are working or not until someone tests it. 
This was due to eclipse checkstyle plugin developers uses short name convention despite checkstyle supports both short name and full name convenion.

**Comment by yamgent** [comment]
@eugenepeh I think he means that you are supposed to put it inside the commit message. :P

**Comment by CanIHasReview** [comment]
# v4

@eugenepeh submitted v4 for review.

* [v4 1/1] [checkstyle: fix module name error](https://github.com/se-edu/addressbook-level4/pull/279/commits/e5181c69d5f6f65b9a38bfa8884a8b10c0fccb8c)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...e5181c69d5f6f65b9a38bfa8884a8b10c0fccb8c)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/4f4770a09395f4f61388f918f838a6e85d98609f~1...4f4770a09395f4f61388f918f838a6e85d98609f))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v5

@eugenepeh submitted v5 for review.

* [v5 1/1] [checkstyle: make Eclipse Checkstyle Plugin recognize all exist modules](https://github.com/se-edu/addressbook-level4/pull/279/commits/63efb0cb9977706405f809741a3e05c5d2e9152d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...63efb0cb9977706405f809741a3e05c5d2e9152d)) ([:chart_with_upwards_trend: Interdiff between v4 and v5](https://github.com/se-edu/addressbook-level4/compare/7c448e457f8134fd88efccfaeebfc3aa601d5d39~1...7c448e457f8134fd88efccfaeebfc3aa601d5d39))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/5/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by eugenepeh** [comment]
Thanks for the review @pyokagan , I apologise that my commit message is confusing.

I have tweaked the commit title from enabled to exist because in Checkstyle Configuraton,
it is possible to temporary enable / disable the checkstyle rules while preserving the original configurations.

Hope this is acceptable, thanks!

**Comment by eugenepeh** [comment]
@yamgent amended, but was at 70 characters, have to move one word to next line

**Comment by CanIHasReview** [comment]
# v6

@eugenepeh submitted v6 for review.

* [v6 1/1] [checkstyle: make Eclipse Checkstyle Plugin recognizes all existing modules](https://github.com/se-edu/addressbook-level4/pull/279/commits/da737a0729432541ad911cb85c81f06cd69f14e2)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...da737a0729432541ad911cb85c81f06cd69f14e2)) ([:chart_with_upwards_trend: Interdiff between v5 and v6](https://github.com/se-edu/addressbook-level4/compare/99abb28b1ee12fca04c11126b890d0828eb7328d~1...99abb28b1ee12fca04c11126b890d0828eb7328d))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/6/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by yamgent** [comment]
@eugenepeh Sorry I didn't realize that the change would cause it to exceed 72 characters.

Maybe we should remove the `checkstyle:` at the front, since the commit message already kind of indicate that we are doing checkstyle-related changes? @pyokagan, your thoughts on this?

**Comment by pyokagan** [comment]
@yamgent 
> I didn't realize that the change would cause it to exceed 72 characters.

It's okay, 72 characters is just a soft limit.

> Maybe we should remove the checkstyle: at the front, since the commit message already kind of indicate that we are doing checkstyle-related changes?

I'm okay with that.

**Comment by yamgent** [comment]
Don't forget to do a CanIHasReview when you are ready :).

**Comment by damithc** [comment]
@yamgent looks like v6 is pending your review.

**Comment by CanIHasReview** [comment]
# v7

@eugenepeh submitted v7 for review.

* [v7 1/1] [Make Eclipse Checkstyle Plugin recognizes all existing modules](https://github.com/se-edu/addressbook-level4/pull/279/commits/821f5ad99b14c44e349d7bb708e891b19e6b5e48)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/941d0afebe52dc6bd86b60bd4a11861f48273900...821f5ad99b14c44e349d7bb708e891b19e6b5e48)) ([:chart_with_upwards_trend: Interdiff between v6 and v7](https://github.com/se-edu/addressbook-level4/compare/6fb140ead247036a34179900f124348ea61a5bb3~1...6fb140ead247036a34179900f124348ea61a5bb3))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/279/7/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
Good work @eugenepeh 
For future reference, the PR title should match the issue title, including the issue number. I corrected it for this PR.

**Pull request merged**
