### PR TITLE
GUI tests: use setText instead of write #53

### LINKED ISSUE #53: GUI tests: use setText instead of write
I think we can speed up the tests if we set the entire command in one shot instead of typing one letter at a time.

### PR DESCRIPTION
**Pull request by damithc**
Fixes #53 

Speeds up tests about 2m 50s to 2m 10s.

### CODE REVIEW

**Comment by damithc** [comment]
@yl-coder for your review and merging

**Comment by yl-coder** [comment]
.setText doesn't really go thru the GUI layer and setText is just modify the underlying value of the GUI node. If we assume that JavaFX UIControl is working, i think it is fine.

**Comment by damithc** [comment]
.write() is painfully slow. Let's use setText by default. We can use write in some cases, especially if some event handling happens after every keystroke (e.g. live search).

**Comment by yl-coder** [comment]
I'm just thinking of extreme case. For example, If there is parent node consuming the key event. This method will pass the test cases, but the behaviour in reality may be different. 

We can speed up the write method by implementing our own.

**Comment by damithc** [comment]
That kind of 'show stopper' bugs are usually noticed even without automated tests. We can make most of the tests use .setText() but a few tests use .write().
Another thing we can do is to use .setText() for the first n-2 chars and use write for the last 2 chars.

**Comment by damithc** [comment]
Or use write for the first few letters and set text for the remainder. For now, let's merge this. We can add a refinement later.

**Comment by yl-coder** [comment]
Right.

**Pull request merged**
