### PR TITLE
HistoryCommand: Returns previous commands in reverse chronological order #534

### LINKED ISSUE #534: Update HistoryCommand to be more History-like
The HistoryCommand returns elements in chronological order.

This goes against the intuition that history ought to be seen in reverse chronological order.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #534

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [HistoryCommand: Returns previous commands in reverse chronological order](https://github.com/se-edu/addressbook-level4/pull/537/commits/cb63a9d435c95b3590c5ebc9eafc0d30f164a9b9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/5a70b77b2a4679666e12e36fe92dccc4f53f5310...cb63a9d435c95b3590c5ebc9eafc0d30f164a9b9))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/537/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/1] [HistoryCommand: Returns previous commands in reverse chronological order](https://github.com/se-edu/addressbook-level4/pull/537/commits/e9e1e9514564a7a6bdbc90efdd319f35e75ee816)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/5a70b77b2a4679666e12e36fe92dccc4f53f5310...e9e1e9514564a7a6bdbc90efdd319f35e75ee816)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/9f2beba0a9d498798c208d32bdf01ccce844f318~1...9f2beba0a9d498798c208d32bdf01ccce844f318))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/537/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/1] [HistoryCommand: Returns previous commands in reverse chronological order](https://github.com/se-edu/addressbook-level4/pull/537/commits/90f453b39b229604293b83c53636d245c329e103)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/5a70b77b2a4679666e12e36fe92dccc4f53f5310...90f453b39b229604293b83c53636d245c329e103)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/5ad414460556cb66ba970596fce6b4535e7e8864~1...5ad414460556cb66ba970596fce6b4535e7e8864))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/537/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@yamgent last call? :>

**Comment by Zhiyuan-Amos** [comment]
Apologies as I wasn't around during the discussion, so the first thought that came to my mind concerning this change was that it intuitively makes sense to me, thus the commit message.

Since the ResultDisplay remains scrolled all the way up when we display text that is longer than the size of the box, showing the history from most recent to the earliest does make sense, as we would expect the user to want to see what he has typed most recently, and he can scroll down if he wants to see what he has typed earlier. At least this is how it works for Google Chrome History as well.

**Comment by chao1995** [comment]
"I guess we are making an assumption that user will want to see what he has typed most recently, just like how Google Chrome History works." This can be considered additional information to include in commit message. I think it's helpful for me to understand the reason of this change. :)

**Comment by yamgent** [comment]
@Zhiyuan-Amos need you to resolve the merge conflict.

**Comment by CanIHasReview** [comment]
# v4

@Zhiyuan-Amos submitted v4 for review.

* [v4 1/1] [HistoryCommand: Returns previous commands in reverse chronological order](https://github.com/se-edu/addressbook-level4/pull/537/commits/b3326d5a24c6bec60a4195ecbf7d44b402bda822)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/05b883ebfd21e2c3cd8d209ead3dc19852f9c5d2...b3326d5a24c6bec60a4195ecbf7d44b402bda822)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/66a89ebb1389122df8fbfa7cbf9fc895bfdeb68e~1...66a89ebb1389122df8fbfa7cbf9fc895bfdeb68e))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/537/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Pull request merged**
