### PR TITLE
Fix broken links to Developer Guide in docs

### PR DESCRIPTION
**Pull request by limmlingg**

### CODE REVIEW

**Comment by damithc** [comment]
@limmlingg do a site-wide search to ensure there are no other duplicates of the broken link.

**Comment by limmlingg** [comment]
That's all of the links to `DeveloperGuide.md`.

**Comment by CanIHasReview** [comment]
# v1

@limmlingg submitted v1 for review.

* [v1 1/2] [Update link to Developer Guide in README\.md ](https://github.com/se-edu/addressbook-level4/pull/432/commits/5c2c1746a7dc38520e1185900d7b576c1bbfdc63)
* [v1 2/2] [Update links to Developer Guide in LearningOutcomes\.md ](https://github.com/se-edu/addressbook-level4/pull/432/commits/b0d2a3c9c7779ffe3df8083ff6307f89dc61893f)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/cc22ed642b34f15798facec1bddd597aa8c0c395...b0d2a3c9c7779ffe3df8083ff6307f89dc61893f))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/432/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
Can consider squashing these two commits when merging.

**Pull request merged**
