### PR TITLE
HTML anchors in UserGuide.md DeveloperGuide.md all broken #340

### LINKED ISSUE #246: User/Dev Guide: ToC links broken
Links from Table of Contents are broken

### LINKED ISSUE #340: HTML anchors in UserGuide.md DeveloperGuide.md all broken
The HTML anchors in both documents are incorrectly generated. The anchor in the index (the content list at the top of the document) e.g. https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.md**#design**  does not match the actual anchor:
https://github.com/se-edu/addressbook-level4/blob/master/docs/DeveloperGuide.md**#2-design**

### PR DESCRIPTION
**Pull request by VeryLazyBoy**
Fixes #340 
Fixes #246

### CODE REVIEW

**Comment by yamgent** [comment]
@VeryLazyBoy, thanks for your PR! Remember to submit a CanIHasReview when you are done to request for a review. More information is available here: [6. Request a Review](https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md).

**Comment by CanIHasReview** [comment]
# v1

@VeryLazyBoy submitted v1 for review.

* [v1 1/2] [Fix the links inside UserGuide\.md ](https://github.com/se-edu/addressbook-level4/pull/343/commits/f63091957d8edc4e7f0e1c4a37a686272e7766ab)
* [v1 2/2] [Fix the links inside DeveloperGuide\.md ](https://github.com/se-edu/addressbook-level4/pull/343/commits/61fe8bba615ad500c3e683e30ec8250cb4bd4eb2)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/1f784b06cd8055123a5aa5ad06da7a1a0382bffc...61fe8bba615ad500c3e683e30ec8250cb4bd4eb2))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/343/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by VeryLazyBoy** [comment]
@yamgent , really thanks for your instructions!

**Comment by damithc** [comment]
@VeryLazyBoy confirmed links are working in both markdown version and generated GitHub pages version?

**Comment by VeryLazyBoy** [comment]
Yeah, I think so.

 Here is the operation in markdown:
mark


And in the GitHub pages:
gif

**Comment by yamgent** [comment]
@VeryLazyBoy thanks for fixing this. Can confirm that the fix works. :thumbsup:

Just one minor suggestion to the commit messages, otherwise the PR looks fine to me:


> Fix the links inside UserGuide.md

Fix ~~the~~ ToC links ...

**Comment by VeryLazyBoy** [comment]
@yamgent , thanks for your suggestions and I have changed the commit messages. Do I need to submit a CanIHasReview again?

**Comment by MightyCupcakes** [comment]
Yes, you should.

**Comment by CanIHasReview** [comment]
# v2

@VeryLazyBoy submitted v2 for review.

* [v2 1/2] [Fix ToC links inside UserGuide\.md ](https://github.com/se-edu/addressbook-level4/pull/343/commits/57539f80e54c000c08565e4277b60bfb7535f7cc)
* [v2 2/2] [Fix ToC links inside DeveloperGuide\.md ](https://github.com/se-edu/addressbook-level4/pull/343/commits/c4c9fe02f06e65a100d4685473c66eb743dc95b9)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/03ed0f651bfce1eac0e863c61d648fe5672507c7...c4c9fe02f06e65a100d4685473c66eb743dc95b9)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/0517854294616a80c3936ede57197adc89493df5~1...0517854294616a80c3936ede57197adc89493df5))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/343/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@VeryLazyBoy submitted v3 for review.

* [v3 1/2] [UserGuide\.md: add missing numbers to ToC links ](https://github.com/se-edu/addressbook-level4/pull/343/commits/98ad812f3113e7b4292c5b71ad4cf6de375ae7eb)
* [v3 2/2] [DeveloperGuide\.md: add missing numbers to ToC links ](https://github.com/se-edu/addressbook-level4/pull/343/commits/4ca5e64a6e1bcfcde088e593df7db75503ba8e9d)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/03ed0f651bfce1eac0e863c61d648fe5672507c7...4ca5e64a6e1bcfcde088e593df7db75503ba8e9d)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/9415583a1396dbf2020d6c34360b509e4f63b6ad~1...9415583a1396dbf2020d6c34360b509e4f63b6ad))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/343/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by VeryLazyBoy** [comment]
@damithc , thanks for your suggestion and I learnt a lot from this pull request.

**Comment by damithc** [comment]
@VeryLazyBoy one last thing to do: 
You need to add a `Fixes #...` to the PR description so that the relevant issue is auto-closed when this PR is merged.

**Comment by VeryLazyBoy** [comment]
@damithc , the description is added.

**Comment by damithc** [comment]
> but do I need to include #246 ?

I added that.

Thanks for your contribution @VeryLazyBoy 👍 
You are encouraged to continue contributing, working your way through progressively harder issues.

**Comment by VeryLazyBoy** [comment]
@damithc , thank you for your guidance and encouragement! I will have a try on more issues.

**Pull request merged**
