### PR TITLE
Clean XCommandTests #545

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Part of #545

```
XCommandTests use their own assertCommandSuccess(...) and 
assertCommandFailure(...) to verify the test results.

As CommandTestUtil have similar methods, XCommandTests should use
them instead.

Let's teach them to use the common methods located in 
CommandTestUtil.
```

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/6] [Combine both CommandTestUtil classes](https://github.com/se-edu/addressbook-level4/pull/544/commits/811ef46cb8959af32f8c1a01bdacd3af732ab2eb)
* [v1 2/6] [AddCommandIntegrationTest: Use CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/11ad69befa1258e62562ede18cc0f6d342059ade)
* [v1 3/6] [ClearCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/5848ff029b74f12a37634759bc0f8da256eda424)
* [v1 4/6] [ListCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/fc88cd5eea397577cafb60c7575e745e7686ec73)
* [v1 5/6] [DeleteCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/41a15c8ed93963f9bcb173b257fb819cbcedeafe)
* [v1 6/6] [EditCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/93f9861de3d9730ed405e100146e47279a59a4e7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/a817b56dff2a2061049ba053b67093c1c8bcafe3...93f9861de3d9730ed405e100146e47279a59a4e7))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/544/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by yamgent** [comment]
`FindCommandTest` also uses `assertCommandSuccess()`, are we not cleaning that up too?

**Comment by Zhiyuan-Amos** [comment]
`FindCommandTest`'s `assertCommandSuccess` is different from the `assertCommandSuccess` that the other tests use. We are not creating a Model for the `FindCommandTest`'s `assertCommandSuccess`, but the other tests are.

**Comment by Zhiyuan-Amos** [comment]
@yamgent I suppose you are fine with the architecture since you're alrd nitting. I will ask prof to vet the architecture first.

**Comment by Zhiyuan-Amos** [comment]
@damithc prof, for your architecture review, thank you!

**Comment by Zhiyuan-Amos** [comment]
@damithc prof gentle reminder for your review :)

**Comment by Zhiyuan-Amos** [comment]
@yamgent @limmlingg , let the nitting begin :) @yamgent do you have any other comments apart from the commit messages?

**Comment by yamgent** [comment]
@Zhiyuan-Amos I rechecked, generally looks OK.

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/6] [Combine both CommandTestUtil classes](https://github.com/se-edu/addressbook-level4/pull/544/commits/fa654d9636adc51cdc3e62afb166e91220de4862)
* [v2 2/6] [AddCommandIntegrationTest: Use CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/3f001cc89a5cde000d1b18368781fff41e000d0b)
* [v2 3/6] [ClearCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/efefc3d659ecc7bd43d5dc820b917bf0c4907570)
* [v2 4/6] [ListCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/59b842d0f73ea50d3a11d615652845da12af84c2)
* [v2 5/6] [DeleteCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/4fc50d9819c70632b8d0f2adad01bac2e3d2dd72)
* [v2 6/6] [EditCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/634d3814dc478294cf2b4aff3563a1b80d80d6ae)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/3e71299fdd455bdd42ba4768bcc26fbddbd82cfc...634d3814dc478294cf2b4aff3563a1b80d80d6ae)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/23e03d6463cab6a432d40068cd90b9647d9213ba~1...23e03d6463cab6a432d40068cd90b9647d9213ba))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/544/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/6] [Combine both CommandTestUtil classes](https://github.com/se-edu/addressbook-level4/pull/544/commits/fa654d9636adc51cdc3e62afb166e91220de4862)
* [v3 2/6] [AddCommandIntegrationTest: Use CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/9c6d89080e6671aee5e151659b473730eacc1616)
* [v3 3/6] [ClearCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/aa8aeaf02f795944936f63ddcf0b1b18f07e6082)
* [v3 4/6] [ListCommandTest: Use CommandTestUtil\#assertCommandSuccess\(\.\.\.\)](https://github.com/se-edu/addressbook-level4/pull/544/commits/59fa74867986e3a2889d7ec761b1e92475f5d46e)
* [v3 5/6] [DeleteCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/09cc03796fd832cab610ca3678bb499c740fe483)
* [v3 6/6] [EditCommandTest: Static import CommandTestUtil methods](https://github.com/se-edu/addressbook-level4/pull/544/commits/750613018859af887a9ff8e2c069196b2a1a87f8)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/3e71299fdd455bdd42ba4768bcc26fbddbd82cfc...750613018859af887a9ff8e2c069196b2a1a87f8)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/d31b9220578748b9b9c213a69f3e86004eaa0f53~1...d31b9220578748b9b9c213a69f3e86004eaa0f53))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/544/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@limmlingg require your approval here!

**Pull request merged**
