### PR TITLE
Tweak Gradle preferences file

### PR DESCRIPTION
**Pull request by damithc**
Tweaked this file because Eclipse added it during the set up process, and gives an error if I remove it.

### CODE REVIEW

**Comment by damithc** [comment]
@m133225 @okkhoy can you try this branch and see if your eclipse project still works?

**Comment by okkhoy** [comment]
I can try it tomorrow morning, since I don;t have my laptop now :-/

**Comment by m133225** [comment]
Reimported the project and it seems to work for me.

**Comment by okkhoy** [comment]
works now as well. all tests pass too! same observation, eclipse deletes the added line.

**Comment by damithc** [comment]
Ha ha, in some comps, it adds the line if its missing. In others, it deletes the line if added. :-p

**Comment by damithc** [comment]
On my computer it doesn't delete the added line.
@m133225 I wonder if we can omit the eclipse project files and let eclipse generate them during the import process.

**Comment by m133225** [comment]
@damithc I think that there are some required eclipse project files in order for it to be imported successfully. However, it seems to work well even if `.settings/org.eclipse.buildship.core.prefs` is removed before importing. The buildship plugin probably re-evaluates the `build.gradle` script.

**Pull request merged**
