### PR TITLE
Fix typo in LogsCenter#getLogger(...) header comment #344

### LINKED ISSUE #344: Fix typo in LogsCenter#getLogger(...) header comment

### PR DESCRIPTION
**Pull request by VeryLazyBoy**
Fixes #344

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@VeryLazyBoy submitted v1 for review.

* [v1 1/1] [Fix minor typos in LogsCenter ](https://github.com/se-edu/addressbook-level4/pull/345/commits/1b71477306b5a40e57690b1db5c03440b555f8a7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/f5efb728b72c193913006d96d4d5591da810af50...1b71477306b5a40e57690b1db5c03440b555f8a7))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/345/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by VeryLazyBoy** [comment]
@MightyCupcakes , thanks for your suggestion.

**Comment by CanIHasReview** [comment]
# v2

@VeryLazyBoy submitted v2 for review.

* [v2 1/1] [Fix typo in LogsCenter\#getLogger\(\.\.\.\) header comment ](https://github.com/se-edu/addressbook-level4/pull/345/commits/c16fd3991e2d1fb3942462292e111423d12b404a)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/f5efb728b72c193913006d96d4d5591da810af50...c16fd3991e2d1fb3942462292e111423d12b404a)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/a5eff63c6d382cf9dd519d37b78019f6ded8f865~1...a5eff63c6d382cf9dd519d37b78019f6ded8f865))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/345/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@VeryLazyBoy I updated issue/PR title to be more descriptive. Thanks for the contribution. If you do more PRs, move on to progressively harder issues.

**Comment by VeryLazyBoy** [comment]
I think I am familiar with the PR process now and I will keep an eye on harder issues.

**Pull request merged**
