### PR TITLE
LearningOutcomes.adoc: tweak to refer to se-book

### PR DESCRIPTION
**Pull request by damithc**
Removed resources listed and pointed to the relevant sections of the se-book instead.

### CODE REVIEW

**Comment by damithc** [comment]
@Zhiyuan-Amos need your help to takeover this PR and carry it to completion. Don't have time to do it myself.

**Comment by Zhiyuan-Amos** [comment]
ok, will do so tonight.

**Comment by Zhiyuan-Amos** [comment]
done. Prof I can't submit a review here cos only PR owner can do so.

The 2nd commit is meant to show the changes that I made (which undone a bit of your work in the first commit, as such require you to check whether they are ok).

**Comment by damithc** [comment]
> The 2nd commit is meant to show the changes that I made (which undone a bit of your work in the first commit, as such require you to check whether they are ok).

Your changes look fine @Zhiyuan-Amos. Thanks for catching the mistakes.

**Comment by Zhiyuan-Amos** [comment]
Should I merge this?

**Comment by damithc** [comment]
Yes, go ahead.

**Pull request merged**
