### PR TITLE
Convert ClearCommandTest to a system test #551

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Part of #551.

```
Tests in the 'guitests' packages, such as ClearCommandTest, merely
concern themselves with the relevant GUI components and the model, and
do not verify other parts of the application (e.g. storage, status bar,
...).

They do not fully qualify as system tests, and we already have
unit tests and integration tests for commands, thus making them
redundant. Also, without any system tests in the codebase, we are unable
to demonstrate to the students how one should be written.

Let's convert ClearCommandTest to a system test.
```

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/2] [Convert ClearCommandTest to ClearCommandSystemTest](https://github.com/se-edu/addressbook-level4/pull/639/commits/c53dd59985362f28fb8fd4e1b1bf3b5754e0f26b)
* [v1 2/2] [ClearCommandSystemTest: Add additional tests](https://github.com/se-edu/addressbook-level4/pull/639/commits/d90ed636e097d5d889470e4706bdd21cba23acd6)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e32a1e791badb4acfe80365177b0600826dcfee1...d90ed636e097d5d889470e4706bdd21cba23acd6))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/639/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
Add test: `FindCommand` following by `ClearCommand`

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/2] [Convert ClearCommandTest to ClearCommandSystemTest](https://github.com/se-edu/addressbook-level4/pull/639/commits/2a0aecb802d4398055ebadde64698fe76766f710)
* [v2 2/2] [ClearCommandSystemTest: Add additional tests](https://github.com/se-edu/addressbook-level4/pull/639/commits/2a19e96e9cdae41b7f5e0f735b59575f3d6f9e5e)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/e32a1e791badb4acfe80365177b0600826dcfee1...2a19e96e9cdae41b7f5e0f735b59575f3d6f9e5e)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/e48f2d9f95fcc96baf1b91ecfe94d86325b73b3e~1...e48f2d9f95fcc96baf1b91ecfe94d86325b73b3e))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/639/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
Cleaned up a bit.

**Comment by Zhiyuan-Amos** [comment]
Made the code cleaner; ignore v.1

**Comment by Zhiyuan-Amos** [comment]
@yamgent since you've already approved the other 2 PRs, here's one more for you to review :P

**Comment by Zhiyuan-Amos** [comment]
@damithc tagging you in for review since system tests are due in the coming week (Week 4) and there shouldn't be major issues with this PR apart from possible missing test cases.

**Pull request merged**
