### PR TITLE
User can edit a person's details #141

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Ready for review

Functionalities:
1. User can remove existing tags by typing "t/" without any tags behind it.
2. Syntax of edit is similar to that of add (refer to UG), but you do not have to necessarily edit all the fields.

### CODE REVIEW

**Comment by damithc** [comment]
@pyokagan can review this one? It's a big one. :-p
@Zhiyuan-Amos we don't align descriptions of @param and @return elements in header comments

**Comment by pyokagan** [comment]
@damithc 
> @pyokagan can review this one? It's a big one. :-p

Okay. Can keep this PR in view as well? Implementing the "edit a person" functionality will require us to make some fundamental decisions on how the model APIs are designed, which will in turn affect all other components that depend on it.

e.g. the most pressing question on my mind is: should `Person` be mutable or immutable? What are the trade-offs of each option?

**Comment by pyokagan** [comment]
@Zhiyuan-Amos I won't have time to review this in the next 10+ hours, so in the meantime could you consider cleaning up the organization of commits in this PR? It contains a lot of fixup commits and noise.

So, code review has to be an extremely careful process because a single subtle error in a line of code can introduce bugs. This PR contains 500+ lines of code, and staring at a diff of 500+ lines will usually make reviewers miss any subtle errors in the code. So, reviewers will have to go through it multiple times just to make sure, which takes up a lot of time and effort on their part. In OSS projects where reviewers are not paid and they are just doing it as a side-hobby thing, this may lead to too large PRs getting dropped.

Instead, you can help the reviewer by organizing your commits well. Each commit should contain a single logical change, with its commit message explaining that change. Reviewers can then review the PR in bite-sized commits, which will allow them to manage the complexity of the PR much more easily.

What is a "logical change"? Hard to explain because it does not have a strict definition AFAIK. However, for now I think #202 for example is a PR of similar size to this PR that is pretty decent with its organization of commits. You may wish to take a look at that.

For how to re-organize the commits in this PR: you can look up interactive rebase, or maybe redo the branch from scratch.

**Comment by Zhiyuan-Amos** [comment]
@pyokagan Hello, thanks so much for the tip for newbies like myself. I have redone a new PR over at this link: https://github.com/se-edu/addressbook-level4/pull/209

**Pull request closed without merging**
