### PR TITLE
Fix links inside both UserGuide.md and DeveloperGuide.md

### PR DESCRIPTION
**Pull request by VeryLazyBoy**

### CODE REVIEW

**Comment by acjh** [comment]
Use [generic numbering](https://github.com/oss-generic/process/blob/e657c5f6a35929815a1e3f04b65b4226b9886366/codingStandards/CodingStandard-Gfmd.md#use-generic-numbering-for-ordered-list)?

**Comment by VeryLazyBoy** [comment]
is it possible to use generic numbering for element ids?

**Comment by acjh** [comment]
Nope, I meant the TOC list.

Anyway, an identical fix was tried and reverted. Please see @damithc's comments in #246.

**Comment by VeryLazyBoy** [comment]
Yeah, I see. Thanks for your suggestion and I will close this PR

**Comment by acjh** [comment]
No problem. Thanks for attempting a fix; you're welcome to tackle another issue :)

**Comment by acjh** [comment]
@VeryLazyBoy As per the discussion in #340, would you like to re-submit the above fix?
If you are keen, please [rename the branch](https://github.com/oss-generic/process/blob/master/docs/FormatsAndConventions.md#branch) and submit a PR [according to these guidelines](https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md#submitting-a-pr).

**Comment by VeryLazyBoy** [comment]
Yeah, sure.

**Pull request closed without merging**
