### PR TITLE
Upgrade Checkstyle to version 8.1 #604

### LINKED ISSUE #604: Upgrade checkstyle to 8.1
The current version of checkstyle that we are using is 7.2.

We could use an upgrade, as the latest release is 8.1. The latest version of [IntelliJ's checkstyle-IDEA plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) already supports 8.1, and students will likely get confused if the plugin (using 8.1 by default) reports different errors from gradle (now on 7.2)

1. Upgrade checkstyle to 8.1.
1. Fix checkstyle.xml because checkstyle 8.1 will complain that: `SuppressionCommentFilter is not allowed as a child in Checker.`
1. Fix new formatting issues inside the codebase, as reported by checkstyle due to the upgrade.

---

The fix for (1) and (2) are as follows:
```diff
diff --git a/build.gradle b/build.gradle
index d8432a8..51a0071 100644
--- a/build.gradle
+++ b/build.gradle
@@ -42,7 +42,7 @@ allprojects {
         junitVersion = '4.12'
         testFxVersion = '4.0.5-alpha'
         monocleVersion = '1.8.0_20'
-        checkstyleVersion = '7.2'
+        checkstyleVersion = '8.1'

         libDir = 'lib'
     }
diff --git a/config/checkstyle/checkstyle.xml b/config/checkstyle/checkstyle.xml
index 13fc915..45a7c4a 100644
--- a/config/checkstyle/checkstyle.xml
+++ b/config/checkstyle/checkstyle.xml
@@ -25,17 +25,16 @@
     <property name="message" value='TODO is preferred to FIXME."' />
   </module>

-
-  <!-- Required to allow exceptions in code style -->
-  <module name="SuppressionCommentFilter">
-    <property name="offCommentFormat" value="CHECKSTYLE.OFF\: ([\w\|]+)"/>
-    <property name="onCommentFormat" value="CHECKSTYLE.ON\: ([\w\|]+)"/>
-    <property name="checkFormat" value="$1"/>
-  </module>
-
   <!-- All Java AST specific tests live under TreeWalker module. -->
   <module name="TreeWalker">

+    <!-- Required to allow exceptions in code style -->
+    <module name="SuppressionCommentFilter">
+      <property name="offCommentFormat" value="CHECKSTYLE.OFF\: ([\w\|]+)"/>
+      <property name="onCommentFormat" value="CHECKSTYLE.ON\: ([\w\|]+)"/>
+      <property name="checkFormat" value="$1"/>
+    </module>
+
     <!-- Required for SuppressionCommentFilter to work -->
     <module name="FileContentsHolder"/>

```

The fix for (3) is simply to remove the extra empty lines:

dontleaveline

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #604.

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
@yamgent you should have just done this PR on your own. I just forked whatever you mentioned in the issue... XD

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [Upgrade Checkstyle to version 8\.1](https://github.com/se-edu/addressbook-level4/pull/614/commits/729270817110fdb502e61a5f8b2993afaa4586d7)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/816f07f953e8855556176cc0b6f9ca8a13a7b0f7...729270817110fdb502e61a5f8b2993afaa4586d7))
<details>
<summary>Checkout this PR version locally</summary>

```sh
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/614/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you wish to fetch this PR to.

</details>

**Comment by eugenepeh** [comment]
Hi @Zhiyuan-Amos, how come the SuppressCommentFilter is moved to inside the treewalker?
The checkstyle plugin seems to be broken due to that on my end.
image

**Comment by Zhiyuan-Amos** [comment]
As what @yamgent mentioned in #604. Checkstyle doesn't fail on my side though :O

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos hmm ic, it fails for Eclipse plug-in though, 
It may be version mismatch for between Eclipse cs and Gradle cs. I will look into it.

Just to check, do you use the Eclipse Checkstyle plug-in as well?
Thanks

**Comment by Zhiyuan-Amos** [comment]
Hey @eugenepeh , we are using IntelliJ plug-in ^^

**Comment by eugenepeh** [comment]
@Zhiyuan-Amos oh yes... totally forgot we moving to IntelliJ... Thanks

**Pull request merged**
