### PR TITLE
Delete ui tests

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Debugging #675. @damithc can verify if `AddCommandTest` passes locally?

### CODE REVIEW

**Comment by damithc** [comment]
Passed both times I tried.

**Comment by Zhiyuan-Amos** [comment]
> Passed both times I tried.

This means that you executed the tests twice and both works right? Not that you executed the tests on master branch, and executed the tests on this branch, and both works right? Just clarifying ^^

If it is the former:
As Wang Leng guesses that this bug is caused by an error with TestFX, I can think of 2 ways to resolve this:

1. Simply mention in `DeveloperGuide` that the tests will fail locally because of a bug with TestFX. This doesn't resolve the issue, but at least we inform the developers.
2. Force Gradle to execute `seedu.address.ui` package last. This is a workaround, because the reason why `AddCommandTest` fails is that it is executed after `seedu.address.ui`. (the error is caused by `seedu.address.ui`).

**Comment by Zhiyuan-Amos** [comment]
Oh right yes, cos Gradle starts a new JVM per test or something like that? Ok will do so.

**Comment by damithc** [comment]
Note that I'm not using Gradle to run tests. In my IDEA set up (done based on the instruction in our dev guide), tests are not delegated to gradle. They run within IDEA as per normal.

**Comment by Zhiyuan-Amos** [comment]
Thanks for the note prof.

I tried running all tests using both `Gradle Test Runner` (i.e. tests that are delegated to gradle) and `Platform Test Runner` (i.e. tests that aren't delegated to gradle) on `master branch`, and they both fail. However, when I execute `allTests` using Gradle, the tests pass on `master branch`.

(I tried running all tests `on this branch` using `Gradle Test Runner`, `Platform Test Runner` and executing `allTests` using Gradle, and they all pass.)

As such, the only way is to pass all tests on `master branch` is to execute `allTests` using Gradle.

**Comment by Zhiyuan-Amos** [comment]
Solution written by Paul https://github.com/se-edu/addressbook-level4/issues/675#issuecomment-330775347

**Pull request closed without merging**
