### PR TITLE
Add se-edu branding + navigation bar to website

### PR DESCRIPTION
**Pull request by pyokagan**
Surprise!

<sup>jk this won't be finished until June</sup>

### CODE REVIEW

**Comment by pyokagan** [comment]
@damithc Can I have a high-res pic of the SE-EDU logo?

**Comment by pyokagan** [comment]
@damithc Nevermind, I managed to crop out a 286x286 res one from the one on se-edu.github.io.

logocropped

If you have something more high res than that (maybe 512x512?) then that would be fine as well.

**Comment by damithc** [comment]
How about this one?
image
Unfortunately, PowerPoint seems to lose resolution when converting to an image :-p
If you use this image, replace logo.pptx with this one too.
[logo.pptx](https://github.com/se-edu/addressbook-level4/files/2154055/logo.pptx)

**Comment by pyokagan** [comment]
@damithc 
> If you use this image, replace logo.pptx with this one too.

Maybe we should just maintain the logo.pptx file in the se-edu.github.io repo?

**Comment by damithc** [comment]
> Maybe we should just maintain the logo.pptx file in the se-edu.github.io repo?

yes, that's what I had in mind actually (the file is there already). I was under the wrong impression that this PR is in that repo :-p
Just push the new version to se-edu.github.io

**Comment by pyokagan** [comment]
Travis gave up on this PR, will open a new one.

**Pull request closed without merging**
