### PR TITLE
Rework how TypicalTestPersons exposes its persons #221

### LINKED ISSUE #221: Rework how TypicalTestPersons exposes its persons
Eclipse gives the following warnings about the usage of `TypicalTestPersons`:
```
Description	Resource	Path	Location	Type
The static field TypicalTestPersons.alice should be accessed in a static way	AddCommandTest.java	/addressbook-level4/src/test/java/guitests	line 34	Java Problem
The static field TypicalTestPersons.benson should be accessed in a static way	CommandBoxTest.java	/addressbook-level4/src/test/java/guitests	line 11	Java Problem
The static field TypicalTestPersons.benson should be accessed in a static way	FindCommandTest.java	/addressbook-level4/src/test/java/guitests	line 14	Java Problem
The static field TypicalTestPersons.daniel should be accessed in a static way	FindCommandTest.java	/addressbook-level4/src/test/java/guitests	line 14	Java Problem
The static field TypicalTestPersons.daniel should be accessed in a static way	FindCommandTest.java	/addressbook-level4/src/test/java/guitests	line 18	Java Problem
The static field TypicalTestPersons.hoon should be accessed in a static way	AddCommandTest.java	/addressbook-level4/src/test/java/guitests	line 18	Java Problem
The static field TypicalTestPersons.hoon should be accessed in a static way	AddCommandTest.java	/addressbook-level4/src/test/java/guitests	line 28	Java Problem
The static field TypicalTestPersons.hoon should be accessed in a static way	ClearCommandTest.java	/addressbook-level4/src/test/java/guitests	line 17	Java Problem
The static field TypicalTestPersons.hoon should be accessed in a static way	ClearCommandTest.java	/addressbook-level4/src/test/java/guitests	line 18	Java Problem
The static field TypicalTestPersons.ida should be accessed in a static way	AddCommandTest.java	/addressbook-level4/src/test/java/guitests	line 23	Java Problem
```
TypicalTestPersons also has a [possible unsafe assignment to static fields](https://github.com/se-edu/addressbook-level4/blob/311ab3c0ccd4d6e49d81234e6d8fe42646e3c834/src/test/java/seedu/address/testutil/TypicalTestPersons.java#L16-L38)

A possible solution is detailed in https://github.com/se-edu/addressbook-level2/pull/120#discussion_r92934320

### PR DESCRIPTION
**Pull request by pyokagan**
Fixes #221

### CODE REVIEW

**Comment by pyokagan** [comment]
@damithc 
In https://github.com/se-edu/addressbook-level2/pull/120#discussion_r92934320 you said:
> May be use static methods instead e.g. amy(), bill() etc. to create new objects every time? That way, we ensure that tests cannot influence each other via shared test objects.

In the AddressBook-Level4 tests this pattern is used quite often:
```java
TypicalTestPersons td = new TypicalTestPersons();
td.hoon, td.ida, ...etc
```
where creating a new instance is used to rename `TypicalTestPersons` to a shorter variable name.

I can see the usefulness of that, so maybe instead of having `alice()`, `benson()` etc. static methods we can just make `alice, benson, carl` non-static?

The `alice, benson, ...` fields being static seems strange to me since according to #42 where `TypicalTestPersons` was introduced it seems that the old `TypicalTestData` class used non-static fields as well. Maybe making them static was just a mistake?

CC @yl-coder

**Comment by damithc** [comment]
@pyokagan Yes, going back to non-static person objects sounds like the way to go. Using static objects for testing can cause intermittent state leaks between tests that are quite hard to debug.

**Comment by yl-coder** [comment]
I can't remember why I did it already. I think it was for some workaround. Its a good idea to go back to non-static.

**Comment by pyokagan** [comment]
> Its a good idea to go back to non-static.

Okay, let's do that.

Ready for review.

**Pull request merged**
