### PR TITLE
Replace LogicManagerTest#generatePersonWithName() with PersonBuilder #389

### LINKED ISSUE #389: LogicManagerTest should use PersonBuilder
Both LogicManagerTest#generatePersonWithName() and PersonBuilder’s constructor create Person objects with default values. This makes the former method redundant.

Let’s change the creation of these Person objects to use PersonBuilder’s constructor instead.

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #389

### CODE REVIEW

**Comment by CanIHasReview** [comment]
# v1

@Zhiyuan-Amos submitted v1 for review.

* [v1 1/1] [Update LogicManagerTest to use PersonBuilder](https://github.com/se-edu/addressbook-level4/pull/391/commits/95ce623e4b04d42c621942e6cd68d3e03ef6585a)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/dc9fe96a38a2b5f9bb5bb4c05c3ff1db47b1effd...95ce623e4b04d42c621942e6cd68d3e03ef6585a))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/391/1/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by CanIHasReview** [comment]
# v2

@Zhiyuan-Amos submitted v2 for review.

* [v2 1/1] [Replace LogicManagerTest\#generatePersonWithName\(\) with PersonBuilder](https://github.com/se-edu/addressbook-level4/pull/391/commits/ac9118641d2e5c9ab8d9e8621e4443044e93290b)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/dc9fe96a38a2b5f9bb5bb4c05c3ff1db47b1effd...ac9118641d2e5c9ab8d9e8621e4443044e93290b)) ([:chart_with_upwards_trend: Interdiff between v1 and v2](https://github.com/se-edu/addressbook-level4/compare/2f461855227f4ae4f05274583cf4698f3d7c3848~1...2f461855227f4ae4f05274583cf4698f3d7c3848))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/391/2/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@yamgent Noted! You can tell I'm not that good with commit messages ><

**Comment by CanIHasReview** [comment]
# v3

@Zhiyuan-Amos submitted v3 for review.

* [v3 1/1] [Replace LogicManagerTest\#generatePersonWithName\(\) with PersonBuilder](https://github.com/se-edu/addressbook-level4/pull/391/commits/babd359372d701983ef67b0e5d3ab068915b4a45)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/dc9fe96a38a2b5f9bb5bb4c05c3ff1db47b1effd...babd359372d701983ef67b0e5d3ab068915b4a45)) ([:chart_with_upwards_trend: Interdiff between v2 and v3](https://github.com/se-edu/addressbook-level4/compare/8babc23b96fb976be01f5078ff748aed67ae9cfd~1...8babc23b96fb976be01f5078ff748aed67ae9cfd))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/391/3/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by damithc** [comment]
@Zhiyuan-Amos please fix the conflict.

**Comment by CanIHasReview** [comment]
# v4

@Zhiyuan-Amos submitted v4 for review.

* [v4 1/1] [Replace LogicManagerTest\#generatePersonWithName\(\) with PersonBuilder](https://github.com/se-edu/addressbook-level4/pull/391/commits/d68e3548fdc50631b485d768a4863ebe31c2d287)

([:books: Archive](https://github.com/se-edu/addressbook-level4/compare/8e4d306e4cc579b4e967b267a3c41aafcedbc700...d68e3548fdc50631b485d768a4863ebe31c2d287)) ([:chart_with_upwards_trend: Interdiff between v3 and v4](https://github.com/se-edu/addressbook-level4/compare/aeb505d33a32ce17cdcac76b30ea4b7d6c2c47a7~1...aeb505d33a32ce17cdcac76b30ea4b7d6c2c47a7))
<details>
<summary>Checkout this PR version locally</summary>

```shell
git fetch https://github.com/se-edu/addressbook-level4.git refs/pr/391/4/head:BRANCHNAME
```
where `BRANCHNAME` is the name of the local branch you want to fetch this PR to.

</details>

**Comment by Zhiyuan-Amos** [comment]
@damithc I've resolved the merge conflict. Thanks!

**Pull request merged**
